# Form implementation generated from reading ui file '.\Forms\help.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(771, 404)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(771, 0))
        MainWindow.setMaximumSize(QtCore.QSize(771, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\Forms\\ico.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(620, 310, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Subheading")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton {\n"
"background-color:rgb(208, 215, 255);\n"
"color: black;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 10px;\n"
"border-color :rgb(134, 134, 134);\n"
"padding: 6px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #888;\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"    background-color:rgb(120, 124, 180);\n"
"    color: white;\n"
"}\n"
"")
        self.pushButton_1.setObjectName("pushButton_1")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 40, 731, 261))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("")
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 0, 591, 31))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Помощь"))
        self.pushButton_1.setText(_translate("MainWindow", "Назад"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Calibri\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">Данная программа позволяет вам в автоматическом режиме создать конфигурационный файл WireGuard для конечного клиента на оборудовании MikroTik. Для подключения потребуется ввести корректные данные в разделе «Настройка начальной конфигурации». Подключение происходит по протоколу SSH. У пользователя, при подключении через SSH должны быть права на запись, чтение и удаление параметров WireGuard. Программа сформирует готовый файл конфигурации, который можно передавать клиенту.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">Предварительно у клиента должен быть установлен WireGuard. Клиента можно скачать здесь: </span><a href=\"https://www.wireguard.com/install/\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">https://www.wireguard.com/install/</span></a><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">  </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:14pt; font-weight:600;\">Инструкция по эксплуатации</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">  </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">Для использования программы необходимо предварительно настроить RouterOS:</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">a) Создать учётную запись для настройки;</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">b) Включить SSH</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">c) Создать интерфейс WireGuard с парой приватного и публичного ключа. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">d) Настроить Firewall. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">  </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">Далее необходимо настроить параметры начальной конфигурации в программе. Данная конфигурация включает в себя: </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">1. Конфигурация подключения к MikroTik для создания профиля через SSH</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">1.1. </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">IP управления</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\"> – адрес MikroTik для подключения по SSH;</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">1.2. </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">Порт SSH </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">– порт службы SSH для подключения;</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">1.3. </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">Логин</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\"> – имя пользователя на RouterOS ;</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">1.4. </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">Пароль</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\"> – пароль пользователя на RouterOS (шифруется при вводе);</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">  </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">2. Предварительная конфигурация WireGuard подключения для новых клиентов</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">2.1. </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">Сервер</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\"> – IP адрес или DNS имя к которому будут подключаться клиенты;</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">2.2. </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">Порт </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">– порт на котором находится сервис WireGuard</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">2.3. </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">Имя интерфейса сервера WireGuard</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\"> – название интерфейса WireGuard в RouterOS. Находится в разделе «WireGuard»</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">2.4. </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">Пул IP для клиентов</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\"> (максимальная маска /16) – начальное и конечное значение для пула адресов, IP адрес из которого будет выбран автоматически без повторений для клиента. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">2.5. </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">Адрес сервера в VPN туннеле </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">– IP адрес, который назначается на интерфейс в RoterOS из пункта</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\"> 2.3</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">2.6. </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">DNS сервера</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\"> – адреса DNS, которые будут у клиента.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">2.7. </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">Маршруты в VPN</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\"> – маршруты, которые будут «заворачиваться» в VPN при подключении на стороне клиента. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">  </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">После заполнения всех данных необходимо сохранить конфигурацию. Все данные хранятся в файле «</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">wg_pre_config.conf</span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">» в основном каталоге программы. Некоторые данные в файле зашифрованы для безопасности. Не рекомендуется изменять параметры в конфигурационном файле.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">  </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">Далее на главной странице программы в поле «Имя пользователя» необходимо ввести имя пользователя. К данному имени будет привязана конфигурация клиента. Фактически имя нужно для идентификации настроек и дальнейшему учёту всех подключаемых клиентов. Рекомендуется использовать символы на латинице и цифры. Например: </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">IvanFedotov3 </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">или </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt; font-weight:600;\">i_fedotov </span><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">или иные сочетания букв и цифр. Используйте понятные для вас имена. </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">При нажатии на кнопку «Добавить» немного подождите. Процесс создания конфигурации может происходить до 10 секунд. Время создания напрямую зависит от модели MikroTik.</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">  </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">  </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:14pt; font-weight:600;\">Запуская программу, Вы принимаете условия использования</span><span style=\" font-size:8pt;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial,Helvetica,sans-serif\'; font-size:12pt;\">1. Программа поставляется без каких-либо гарантий. Автор программы не несет ответственности за последствия использования программы.</span><span style=\" font-size:8pt;\"> </span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'MS Shell Dlg 2\';\">Протестировано на версии прошивки RouterOS V 7.6. Версия программы V 1.4</span></p></body></html>"))
